export const MEMBER_EXPORT_FIELDS = [
  { key: "id", label: "ID" },
  { key: "nia", label: "NIA" },
  { key: "front_title", label: "Gelar Depan" },
  { key: "name", label: "Nama" },
  { key: "back_title", label: "Gelar Belakang" },
  { key: "email", label: "Email" },
  { key: "join_year", label: "Tahun Bergabung" },
  { key: "job_title", label: "Jabatan" },
  { key: "administrator_role", label: "Pengurus" },
  { key: "region", label: "Wilayah" },
  { key: "status", label: "Status" },
  { key: "is_active", label: "Aktif" },
  { key: "is_need_verify", label: "Butuh Verifikasi" },
  { key: "is_verified", label: "Sudah Verifikasi" },
  { key: "verification_status", label: "Status Verifikasi" },
  { key: "verification_note", label: "Catatan Verifikasi" },
  { key: "nik", label: "NIK" },
  { key: "place_birth", label: "Tempat Lahir" },
  { key: "date_birth", label: "Tanggal Lahir" },
  { key: "gender", label: "Gender" },
  { key: "citizenship", label: "Kewarganegaraan" },
  { key: "phone", label: "Telepon" },
  { key: "address", label: "Alamat" },
  { key: "province", label: "Provinsi" },
  { key: "city", label: "Kota" },
  { key: "district", label: "Kabupaten/Kecamatan" },
  { key: "last_education_nursing", label: "Pendidikan Keperawatan" },
  { key: "last_education", label: "Pendidikan Formal" },
  { key: "workplace", label: "Tempat Kerja" },
  { key: "hope_in", label: "Harapan" },
  { key: "contribution", label: "Kontribusi" },
  { key: "is_member_payment", label: "Bersedia Bayar" },
  { key: "reason_reject", label: "Alasan Tidak Bersedia" },
  { key: "photo", label: "Foto" },
  { key: "member_payment_file", label: "Bukti Pembayaran" },
  { key: "approved_at", label: "Approved At" },
  { key: "rejected_at", label: "Rejected At" },
  { key: "rejected_note", label: "Rejected Note" },
  { key: "created_at", label: "Created At" },
] as const;

export type MemberExportFieldKey =
  (typeof MEMBER_EXPORT_FIELDS)[number]["key"];
